spring:
  application:
    name: uniqueue-backend
  datasource:
    url: ${RDS_HOSTNAME:jdbc:postgresql://localhost:5432/uniqueue_db}
    username: ${RDS_USERNAME:admin}
    password: ${RDS_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # update/create-drop
    show-sql: true # Shows the SQL commands in the terminal (great for debugging)
    properties:
      hibernate:
        format_sql: true   